In [1]:
import numpy as np

In [10]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
print(type(data))
print(data.shape)
print(data.size)
print(data.dtype)
print(data.nbytes)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
(3, 2)
6
int64
48


In [18]:
matriz = np.array([1, 2, 3], dtype=np.int64)
print(matriz.shape)
print(matriz.dtype)
matriz2 = np.array([11, 12, 13], dtype=np.float16)
print(matriz2)
print(matriz2.dtype)
matriz3 = np.array([1, 2, 3], dtype=np.complex64)
print(matriz3)

(3,)
int64
[11. 12. 13.]
float16
[1.+0.j 2.+0.j 3.+0.j]


In [23]:
mat1 = np.array([1 , 2, 3], dtype = np.complex64)
mat2 = np.array([1 , 2, 3], dtype = np.complex64)
mat3 = mat1 + mat2
print(mat3)
print(mat3.dtype)

[2.+0.j 4.+0.j 6.+0.j]
complex64


In [35]:
#np.sqrt(np.array([-1, 0, 1]));
mat5 = np.sin(np.array([-4, 9, 16], dtype = np.complex64));
print(mat5)
print(mat5.real)
print(mat5.imag)


[ 0.7568025-0.j  0.4121185-0.j -0.2879033-0.j]
[ 0.7568025  0.4121185 -0.2879033]
[-0. -0. -0.]


In [79]:
mat6 = np.ones(4,dtype=np.int32)
print(type(mat6))
print(mat6.dtype)
print(mat6)
mat7 = 6*mat6
print(mat7)

<class 'numpy.ndarray'>
int32
[1 1 1 1]
[6 6 6 6]


In [89]:
mat8 = np.empty(3,dtype=np.int8)
print(mat8.dtype)
print(mat8)
mat8.fill(3)
print(mat8)

int8
[1 1 1]
[3 3 3]


In [86]:
mat9 = np.arange(0.,10.,2.)
print(mat9)
mat10 = np.linspace(0,10,10)
print(mat10)

[0. 2. 4. 6. 8.]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [109]:
mat12 = np.empty(2,dtype=np.int8)
print(mat12)
print(mat12.dtype)
mat12.fill(12)


[12 12]
int8
