In [1]:
def mult5(x):
    r = 5*x
    return r

In [2]:
mult5(4)

20

In [3]:
def suma(x,y):
    return x+y

In [4]:
suma(5,-7)

-2

In [5]:
import numpy as np

In [6]:
def maximo(a,b):
    if a < b:
        return b
    else:
        return a

In [7]:
maximo(34,67)

67

In [8]:
def sumaCom(vec):
    #n = vec.size
    n = len(vec)
    s = 0
    for i in range(n):
        #print("i= ",i)
        s = s + vec[i]
        #print("s = ",s)
    return s

In [9]:
v = np.array([1,2,3,4])
sumaCom(v)

10

In [10]:
s = 0
print(s)
s = s + 1
print(s)
s = s + 1
print(s)

0
1
2


In [11]:
s = 0
print(s)
s += 1
print(s)
s += 1
print(s)


0
1
2


In [12]:
A = np.random.randint(-2,2,(4,4))
print(A)


[[ 1 -2  0 -2]
 [-2  1  1 -2]
 [-1  1  0 -1]
 [-2 -1 -2 -2]]


In [13]:
B = np.append(A,[[0,0,0,0]],axis=0)
print(B,"\n")
#aux = np.transpose(np.array([0,0,0,0,0]))
aux = np.zeros((5,1))
C = np.append(B,aux,axis=1)
print(C,"\n")
C[4,4] = -10
print(C,"\n")

[[ 1 -2  0 -2]
 [-2  1  1 -2]
 [-1  1  0 -1]
 [-2 -1 -2 -2]
 [ 0  0  0  0]] 

[[ 1. -2.  0. -2.  0.]
 [-2.  1.  1. -2.  0.]
 [-1.  1.  0. -1.  0.]
 [-2. -1. -2. -2.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[  1.  -2.   0.  -2.   0.]
 [ -2.   1.   1.  -2.   0.]
 [ -1.   1.   0.  -1.   0.]
 [ -2.  -1.  -2.  -2.   0.]
 [  0.   0.   0.   0. -10.]] 



In [15]:
vec = np.arange(-1.0,2.2,0.2)
np.set_printoptions(precision=2,suppress=True)
print(vec)

[-1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6
  1.8  2. ]


In [62]:
a = np.array([[1, 1,1], [2, 2,2], [3, 3,3]])
print(a)
np.insert(a, [1], [[10.],[100.],[1000.]], axis=1)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


array([[   1,   10,    1,    1],
       [   2,  100,    2,    2],
       [   3, 1000,    3,    3]])

In [27]:
cx = np.linspace(-4,4,4)
cy = np.arctan(x)

In [44]:
n = len(cx)
aux1 = cx.reshape(n,1).tolist()
print(aux1)
aux2 = cy.reshape(n,1).tolist()
print(aux2)
print(type(aux2))
print(len(aux2))

[[-4.0], [-1.3333333333333335], [1.333333333333333], [4.0]]
[[-1.3258176636680326], [-0.9272952180016123], [0.9272952180016121], [1.3258176636680326]]
<class 'list'>
4


In [73]:
A = np.zeros((4,5)) # Matriz para construir la tabla de diferencias divididas 
print(A)
B = A.tolist() 
print(B)
C = np.array(B)
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [86]:
A = np.zeros((4,4)) # Matriz para construir la tabla de diferencias divididas 
print(A)
lista = [[3.],[3.],[3.],[3.]]
np.insert(A,[0],[[3.],[3.],[3.],[3.]], axis = 1) # Inserta cx en la columna 0
np.insert(A,[1],lista, axis = 1) # Inserta cy en la segunda columna


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 3., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 3., 0., 0., 0.]])

In [85]:
a = np.array([[1, 1,1,1], [2, 2,2,2], [3, 3,3,3]])
b = np.zeros((3,3))
lista=[[2.],[2.],[2.]]
print(b)
np.insert(b, [1], lista, axis=1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0., 2., 0., 0.],
       [0., 2., 0., 0.],
       [0., 2., 0., 0.]])