In [9]:
def mult5(x):
    r = 5*x
    return r

In [10]:
mult5(4)

20

In [11]:
def suma(x,y):
    return x+y

In [12]:
suma(5,-7)

-2

In [13]:
import numpy as np

In [14]:
def maximo(a,b):
    if a < b:
        return b
    else:
        return a

In [15]:
maximo(34,67)

67

In [20]:
def sumaCom(vec):
    #n = vec.size
    n = len(vec)
    s = 0
    for i in range(n):
        #print("i= ",i)
        s = s + vec[i]
        #print("s = ",s)
    return s

In [21]:
v = np.array([1,2,3,4])
sumaCom(v)

10

In [18]:
s = 0
print(s)
s = s + 1
print(s)
s = s + 1
print(s)

0
1
2


In [19]:
s = 0
print(s)
s += 1
print(s)
s += 1
print(s)


0
1
2


In [24]:
A = np.random.randint(-2,2,(4,4))
print(A)


[[-2 -2  0  0]
 [ 1  0 -2 -1]
 [-1  0 -1  0]
 [ 0  0  1 -2]]


In [38]:
B = np.append(A,[[0,0,0,0]],axis=0)
print(B,"\n")
#aux = np.transpose(np.array([0,0,0,0,0]))
aux = np.zeros((5,1))
C = np.append(B,aux,axis=1)
print(C,"\n")
C[4,4] = -10
print(C,"\n")

[[-2 -2  0  0]
 [ 1  0 -2 -1]
 [-1  0 -1  0]
 [ 0  0  1 -2]
 [ 0  0  0  0]] 

[[-2. -2.  0.  0.  0.]
 [ 1.  0. -2. -1.  0.]
 [-1.  0. -1.  0.  0.]
 [ 0.  0.  1. -2.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[ -2.  -2.   0.   0.   0.]
 [  1.   0.  -2.  -1.   0.]
 [ -1.   0.  -1.   0.   0.]
 [  0.   0.   1.  -2.   0.]
 [  0.   0.   0.   0. -10.]] 



In [44]:
vec = np.arange(-1.0,2.2,0.2)
np.set_printoptions(precision=2,suppress=True)
print(vec)

[-1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6
  1.8  2. ]
