In [1]:
import numpy as np

In [3]:
#First question
def matriz(n):
    A = np.zeros((n,n))
    for i in range(0,n):
        for j in range(0,n):
            A[i,j] = 1/(i+1+j+1-1)
    return A

print(matriz(5))

[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]


In [ ]:
#Second question
