In [1]:
import numpy as np

In [8]:
a = 3
b = 9
step = 0.25
vec = np.arange(a,b,step)
np.set_printoptions(suppress=True)
print(vec)

[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25
 6.5  6.75 7.   7.25 7.5  7.75 8.   8.25 8.5  8.75]


In [9]:
vec2 = np.linspace(1,3,10)
np.set_printoptions(precision=3 ,suppress=True)
print(vec2)

[1.    1.222 1.444 1.667 1.889 2.111 2.333 2.556 2.778 3.   ]


In [10]:
v = np.array([1,3,4,6],dtype=np.int64)
print(v.dtype)
aux = range(3,31)
x = np.array(aux)
print(x.dtype)
print("v= ", v)
print("x= ", x)
print(x[v])

int64
int32
v=  [1 3 4 6]
x=  [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30]
[4 6 7 9]


In [11]:
u1 = np.append(v,[-1,0.5,2])
print(u1)
print("length of u1 =", u1.size)

[ 1.   3.   4.   6.  -1.   0.5  2. ]
length of u1 = 7


In [12]:
uu = np.array([0, 4, 2, 1])
vv = np.array([3, 5, 4, 7])
ans = vv + 5
print(ans)
sum = uu+vv
print(sum)


[ 8 10  9 12]
[3 9 6 8]


In [13]:
x1 = np.arange(9.).reshape((3, 3)) 
x2 = np.arange(3)
x3 = np.arange(5,14).reshape(3,3)
print(x3)
print(x1)
#print(x2)
#print(x1+x2)
print(x1+x3)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 5.  7.  9.]
 [11. 13. 15.]
 [17. 19. 21.]]


In [14]:
vect = np.ones(10)
for i in range(1,11):
    vect[i-1] = 1/i
np.set_printoptions(precision=2)
print(vect)

[1.   0.5  0.33 0.25 0.2  0.17 0.14 0.12 0.11 0.1 ]


In [15]:
vect = np.ones(100)
for i in range(100):
    vect[i] = (-1)**(i+1)/(2*i+1)

print(vect)

print(vect.max())

[-1.    0.33 -0.2   0.14 -0.11  0.09 -0.08  0.07 -0.06  0.05 -0.05  0.04
 -0.04  0.04 -0.03  0.03 -0.03  0.03 -0.03  0.03 -0.02  0.02 -0.02  0.02
 -0.02  0.02 -0.02  0.02 -0.02  0.02 -0.02  0.02 -0.02  0.01 -0.01  0.01
 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01
 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01
 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01
 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01
 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01 -0.01  0.01
 -0.01  0.01 -0.01  0.01]
0.3333333333333333


In [5]:
mat = np.random.rand(3,2)
print("mat = ", mat)
print("\n")
mat2 = np.random.randint(1,10,size=(3,2))
print("mat2 = ", mat2)
print("\n")
print(mat2.max(axis=1))

mat =  [[0.03896126 0.01722156]
 [0.99161793 0.7520904 ]
 [0.91334246 0.54046106]]


mat2 =  [[2 4]
 [8 1]
 [1 9]]


[4 8 9]


In [17]:
mat3 = np.random.randint(0,3,size=(2,2))
mat4 = np.random.randint(-2,2,size=(2,2))
print("mat3 = ", mat3)
print("mat4 = ", mat4)
print("\n")
prod = mat3*mat4
print(prod)
print("\n")
prod2 = np.matmul(mat3,mat4)
print(prod2)

mat3 =  [[1 0]
 [0 0]]
mat4 =  [[-2 -2]
 [ 0  0]]


[[-2  0]
 [ 0  0]]


[[-2 -2]
 [ 0  0]]


In [18]:
matt2 = np.random.randint(4,size=(4,5))
print(matt2)
aa = matt2[[0,3],1:]
print("\n")
print(aa)

[[1 2 1 2 0]
 [0 0 1 2 3]
 [0 2 1 0 3]
 [1 2 2 3 1]]


[[2 1 2 0]
 [2 2 3 1]]


In [19]:
matt3 = np.random.randint(4,size=(4,5))
print(matt3)
aa = matt3[:,2:4]
print("\n")
print(aa)

[[1 2 2 2 2]
 [3 2 0 0 2]
 [2 3 1 3 2]
 [2 1 2 0 3]]


[[2 2]
 [0 0]
 [1 3]
 [2 0]]


In [20]:
matt = np.arange(9).reshape(3,3)
matt2 = np.random.randint(3,size=(3,4))
print(matt2)
#matt[0,1] = -1000
print("\n")
aa = np.delete(matt2,1,axis=0)
aa2 = np.delete(matt2,[0,2],axis=0)
print(aa2)

[[2 1 2 0]
 [0 0 1 2]
 [2 2 0 0]]


[[0 0 1 2]]


In [21]:
matt3 = np.random.randint(4,size=(4,5))
print(matt3)
aa=np.delete(matt3,slice(0,2),1)
print(aa,"\n") 
print(matt3)

[[1 0 3 0 2]
 [2 0 3 1 1]
 [1 1 1 2 0]
 [2 2 2 0 1]]
[[3 0 2]
 [3 1 1]
 [1 2 0]
 [2 0 1]] 

[[1 0 3 0 2]
 [2 0 3 1 1]
 [1 1 1 2 0]
 [2 2 2 0 1]]


In [22]:
def mayor(x,y):
    if x < y:
        return y
    else:
        return x 

In [23]:
mayor(30,4)

30

In [34]:
def mat(n):
    A = np.ones((n,n))
    for i in range(n):
        for j in range(n):
            if abs(i-j)==1:
                A[i,j] = 0
    return A    

In [35]:
print(mat(4))

[[1. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [1. 1. 0. 1.]]


In [36]:
A = np.ones((2,2),dtype=np.int32)
print(A.dtype)

int32
