Introducción a Python 

Tipos de datos primitivos de Python :

Tipo de dato    | Descripción 
----------------|-------------------
str             | Representa cadenas de caracteres (String)
int             | Representa a un número entero (integer)
float           | Representa un número de punto flotante
complex         | Representa un número complejo
bool            | Representa un valor booleano verdadero o falso
Nonetype        | Representa un valor nulo

In [2]:
nom = "Pedro"
apell = 'Gonzales'

In [11]:
import numpy as np

In [4]:
arr = np.array([[0,2,4],[6,8,10]]) 
app_arr=np.append(arr, [[5,7,9],[13,15,17]],axis = 1)

In [5]:
print(app_arr)

[[ 0  2  4  5  7  9]
 [ 6  8 10 13 15 17]]


In [6]:
arr = np.arange(6) 
print(arr.shape)
b=arr.reshape(2,3) 
print(b)
arr1 = np.arange(9, 14)
print(arr1)
arr2 = np.append(arr, arr1, axis = 0)
print("Appended arr2 : ", arr2)

(6,)
[[0 1 2]
 [3 4 5]]
[ 9 10 11 12 13]
Appended arr2 :  [ 0  1  2  3  4  5  9 10 11 12 13]


In [7]:
v = np.shape(b)
print(v[0])

2


In [8]:
def suma(x):
    s = 0.
    v = np.shape(x)
    for i in range(v[0]):
        for j in range(v[1]):
            s += x[i,j]
    return s

In [9]:
suma(b)

15.0

In [31]:
if 1 == 1:
    print("1 es igual a 1")

1 es igual a 1


In [39]:
nums = [4, 78, 9, 84]
for n in nums:
    print(n)

4
78
9
84


In [41]:
np.arange(4)

array([0, 1, 2, 3])

In [45]:
numero = 0
print('Tabla del 3')
while numero <= 10:
    print(f'{numero * 3}')
    numero += 1
print('Fin')

Tabla del 3
0
3
6
9
12
15
18
21
24
27
30
Fin
