In [5]:
import numpy as np
np.set_printoptions(precision=2,suppress=True)

In [31]:
A = np.random.uniform(-10,11,(3,3))
print(A)
b = np.random.uniform(-10,11,(3,1))
print(b)

[[-9.44  2.92  6.74]
 [-1.94  9.05 -1.74]
 [-2.55 -3.87 -4.89]]
[[ 0.88]
 [-2.24]
 [ 9.96]]


In [32]:
Ab = np.append(A,b,axis=1)
print(Ab)

[[-9.44  2.92  6.74  0.88]
 [-1.94  9.05 -1.74 -2.24]
 [-2.55 -3.87 -4.89  9.96]]


In [33]:
ratio = Ab[1,0]/Ab[0,0]
Ab[1,:] = Ab[1,:] - ratio*Ab[0,:]
print(Ab)

[[-9.44  2.92  6.74  0.88]
 [ 0.    8.45 -3.13 -2.42]
 [-2.55 -3.87 -4.89  9.96]]


In [34]:
ratio = Ab[2,0]/Ab[0,0]
Ab[2,:] = Ab[2,:] - ratio*Ab[0,:]
print(Ab)

[[-9.44  2.92  6.74  0.88]
 [ 0.    8.45 -3.13 -2.42]
 [ 0.   -4.66 -6.71  9.72]]


In [35]:
ratio = Ab[2,1]/Ab[1,1]
Ab[2,:] = Ab[2,:] - ratio*Ab[1,:]
print(Ab)

[[-9.44  2.92  6.74  0.88]
 [ 0.    8.45 -3.13 -2.42]
 [ 0.    0.   -8.43  8.39]]


In [36]:
x = np.zeros((3,1))
x[2,0] = Ab[2,3]/Ab[2,2]
x[1,0] = (Ab[1,3] - Ab[1,2]*x[2,0])/Ab[1,1]
x[0,0] = (Ab[0,3] - Ab[0,2]*x[2,0]-Ab[0,1]*x[1,0])/Ab[0,0]
print(x)

[[-1.  ]
 [-0.65]
 [-0.99]]


In [37]:
print(np.matmul(A,x),"\n")
print(b)

[[ 0.88]
 [-2.24]
 [ 9.96]] 

[[ 0.88]
 [-2.24]
 [ 9.96]]


In [39]:
dim=np.shape(Ab)
print(dim)
dim[0]
dim[1]

(3, 4)


4

In [40]:
def Escalona(A):
    dim=np.shape(A)
    nfil = dim[0]
    ncol = dim[1]
    for j in range(0,ncol):
        for i in range(j+1,nfil+1):
            ratio = A[i,j]/A[j,j]
            A[i,:] = A[i,:] - ratio * A[j,:]
    return A
        

In [44]:
A = np.random.normal(-10,11,(3,3))
b = np.random.normal(-10,11,(3,1))
Escalona(A)

IndexError: index 3 is out of bounds for axis 0 with size 3