In [13]:
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg
import matplotlib.pyplot as plt
import time

In [26]:
N = 10000
A = sp.diags([1, -2, -3], [1, 0, -1], shape=[N, N], format='csc')
A1 = A.todense()
b = -np.ones(N)
print("A= \n",A1)

A= 
 [[-2.  1.  0. ...  0.  0.  0.]
 [-3. -2.  1. ...  0.  0.  0.]
 [ 0. -3. -2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -2.  1.  0.]
 [ 0.  0.  0. ... -3. -2.  1.]
 [ 0.  0.  0. ...  0. -3. -2.]]


In [30]:
st = time.time()
x = sp.linalg.spsolve(A, b)
et = time.time()
elapsed_time = et - st
print('Execution time:', elapsed_time, 'seconds')
print("solution x= \n",x)

Execution time: 0.008502006530761719 seconds
solution x= 
 [ 5.00000000e-01 -2.22044605e-16  5.00000000e-01 ... -1.85185185e-02
  4.44444444e-01 -1.66666667e-01]


In [31]:
st = time.time()
x = np.linalg.solve(A1, b)
et = time.time()
elapsed_time = et - st
print('Execution time:', elapsed_time, 'seconds')
print("solution x= \n",x)

Execution time: 10.795637845993042 seconds
solution x= 
 [ 5.00000000e-01 -2.22044605e-16  5.00000000e-01 ... -1.85185185e-02
  4.44444444e-01 -1.66666667e-01]
